import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={
					'min-h-screen min-w-screen bg-slate-800 flex flex-col justify-center items-center'
				}
			>
				<div className="fixed top-4 left-4">
					<a href="/" className="text-white font-bold text-2xl hover:text-slate-500">
						←
					</a>
				</div>
				{children}
			</body>
		</html>
	);
}
