import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { BackButton } from '@/components/BackButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={
                    'min-w-screen flex min-h-screen flex-col items-center justify-center bg-slate-800'
                }
            >
                <BackButton />
                {children}
            </body>
        </html>
    );
}
